from src.utils import QuestionPair

verba_prima = {
    QuestionPair('servus', ['Sklave', 'Diener']),
    QuestionPair('forum', ['Marktplatz', 'Oeffentlichkeit', 'Forum']),
}.__iter__()

verba_undecima = {
    QuestionPair('sententia', ['Antrag', 'Meinung', 'Satz', 'Sinn']),
    QuestionPair('bellum', ['Krieg']),
    QuestionPair('oppidum', ['befestigter Platz', 'Stadt']),
    QuestionPair('proelium', ['Kampf', 'Schlacht']),
    QuestionPair('labor', ['Anstrengung', 'Arbeit']),
    QuestionPair('censor', ['Zensor']),
    QuestionPair('consul', ['Konsul']),
    QuestionPair('miles', ['Soldat']),
    QuestionPair('legio', ['Legion']),
    QuestionPair('ops', ['Hilfe', 'Kraft', 'Macht', 'Mittel', 'Reichtum']),
    QuestionPair('caput', ['Kopf', 'Haupt', 'Hauptstadt']),
    QuestionPair('moenia', ['(Stadt-)Mauern']),
    QuestionPair('altus', ['hoch', 'tief']),
    QuestionPair('vivus', ['lebend', 'lebendig']),
    QuestionPair('meus', ['mein']),
    QuestionPair('tuus', ['dein']),
    QuestionPair('suus', ['sein', 'ihr', 'seine', 'ihre']),
    QuestionPair('noster', ['unser']),
    QuestionPair('vester', ['euer']),
    QuestionPair('alius', ['ein anderer']),
    QuestionPair('unus', ['ein(er)', 'ein einziger']),
    QuestionPair('cuncti', ['alle']),
    QuestionPair('narrare', ['erzaehlen']),
    QuestionPair('restare', ['uebrig bleibem', 'Widerstand leisten']),
    QuestionPair('censere', ['meinen', 'einschaetzen']),
    QuestionPair('manere', ['bleiben', 'warten']),
    QuestionPair('amittere', ['aufgeben', 'verlieren']),
    QuestionPair('animadvertere', ['bemerken', 'wahrnehmen']),
    QuestionPair('premere', ['(unter-)druecken', 'bedraengen']),
    QuestionPair('vincere', ['(be-)siegen', 'uebertreffen']),
    QuestionPair('aperire', ['aufdecken', 'oeffnen']),
    QuestionPair('e/ex', ['aus etw', 'von etw her']),
    QuestionPair('postquam', ['nachdem']),
    QuestionPair('non solum .. sed etiam', ['nicht nur .. sondern auch']),
    QuestionPair('quoque', ['auch']),
    QuestionPair('equidem', ['(ich) allerdings', 'freilich']),
    QuestionPair('solum', ['nur']),
    QuestionPair('vero', ['aber']),
    QuestionPair('alius .. alius', ['der eine .. der andere']),
    QuestionPair('Romam', ['nach Rom'])
}
