<textinp>:
	title: 'InputDialog'
	auto_dismiss: False
	id: text_input

	RelativeLayout:
		orientation: 'vertical'
		pos: self.pos
		size: root.size

        Label:
            text: app.get_question()
            font_size: '30sp'
            size: self.texture_size

		TextInput:
			id: input
			hint_text:'Please Answer the Question'
			pos_hint: {'center_x': 0.5, 'center_y': 0.8}
			size_hint: 0.6, 0.06
            focus: True
            multiline: False
			on_text_validate: app.process()

